title: Microdosing Study
baseurl: 'https://mdstudy.netlify.app/'
copyright: ''
enableGitInfo: no
defaultContentLanguage: en
hasCJKLanguage: no
defaultContentLanguageInSubdir: no
removePathAccents: yes
summaryLength: 30
paginate: 10
enableEmoji: yes
enableRobotsTXT: yes
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
  section:
    - HTML
    - RSS
mediaTypes:
  application/manifest+json:
    suffixes: webmanifest
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
  tableOfContents:
    endLevel: 3
    startLevel: 2
imaging:
  anchor: smart
  quality: 75
  resampleFilter: lanczos
taxonomies:
  author: authors
  category: categories
  tag: tags
related:
  includeNewer: yes
  indices:
    - name: tags
      weight: 80
    - name: categories
      weight: 70
  threshold: 80
  toLower: yes
module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/themes/hello-world
    #- path: github.com/wowchemy/wowchemy-hugo-modules/netlify-cms-academic
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy
